# Site settings
title: "Season to Taste"
tagline: "A community-driven recipe collection"
description: "A community-driven recipe collection where friends share, cook, and enjoy meals together."
url: "https://bigchif33.github.io"
baseurl: "/season-to-taste" # If your repository name is 'season-to-taste'

# Theme settings (Use Chirpy correctly)
remote_theme: "cotes2020/jekyll-theme-chirpy"

# Plugins (Ensure Jekyll processes the theme properly)
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Navigation (Add categories if needed)
navbar:
  - title: "Home"
    url: /
  - title: "Recipes"
    url: /recipes/

# SEO & Social settings (Customize as needed)
author:
  name: "Season to Taste Community"
  email: "your-email@example.com"

# Analytics (Optional, only if you have Google Analytics)
analytics:
  google:
    id: "UA-XXXXXXXXX-X"

# Pagination (Control how many posts show per page)
paginate: 10
paginate_path: "/page:num/"

# Enable Tags & Categories
tag_archive:
  type: liquid
  path: /tags/

category_archive:
  type: liquid
  path: /categories/
