# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Site settings
title: "Season to Taste"
tagline: "A community-driven recipe collection"
description: "A minimal, responsive, and feature-rich Jekyll theme for technical writing."
lang: en
timezone: Australia/Melbourne

# URL settings
url: "https://bigchif33.github.io"
baseurl: "/season-to-taste" # If your site is at the root of the domain, use "/"

# Author settings
author:
  name: "Tom Davidson"
  email: "thomasdavidson28@gmail.com"

# Social settings
github:
  username: bigchif33
twitter:
  username: 

# Analytics (optional)
analytics:
  google:
    id: # Your Google Analytics Tracking ID

# Comments (optional)
comments:
  provider: # e.g., disqus
  disqus:
    shortname: # Your Disqus shortname

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions

# Other settings
markdown: kramdown
highlighter: rouge
